networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - dev

  backend:
    build:
      context: ./FastAPI
    env_file:
      - ./FastAPI/.env
    networks:
      - dev
    depends_on:
      - db


  frontend:
    build:
      context: ./React/watch-together
    networks:
      - dev

  db:
    image: postgres:16
    env_file:
      - ./FastAPI/.env
    ports:
      - "5432:5432"
    networks:
      - dev
    volumes:
      - db_data:/var/lib/postgresql/db_data

volumes:
  db_data: